version: '3.3'

services:
  db_backend_vant:
    container_name: db_backend_vant
    image: mongo:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db_backend_vant
    env_file: .env
    command: mongod --port ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  backend_vant:
    build: .
    container_name: backend_vant
    ports:
      - ${APPLICATION_PORT}:3000
    env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db_backend_vant


